### ISSUE TITLE
mapa mental 

### ISSUE THREAD

**Issue by chelui5** [SistemasTecTlaxiaco/actividad-4-mapa-mental-chelui5#2]
[conjuntos .pdf](https://github.com/user-attachments/files/17093337/conjuntos.pdf)

**Comment by Evelyn-sj13** [comment]
Exposición de Ideas Centrales:4/5
Redacción y Ortografía:3/5
Presentación visual:3/5
Referencias:5/5
Calificación Final:15/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
